"""Updated User Broker migration

Revision ID: 0c7edac6850e
Revises: b654b16957c3
Create Date: 2025-06-19 23:03:49.947140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7edac6850e'
down_revision: Union[str, None] = 'b654b16957c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_brokers', ['client_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_brokers', type_='unique')
    # ### end Alembic commands ###
