"""Updated User Broker migration

Revision ID: b654b16957c3
Revises: 8d24d82523e6
Create Date: 2025-06-19 23:01:15.053779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b654b16957c3'
down_revision: Union[str, None] = '8d24d82523e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.add_column('user_brokers', sa.Column('feed_token', sa.Text(), nullable=True))
    op.drop_column('user_brokers', 'user_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_brokers', sa.Column('user_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_brokers', 'feed_token')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
